config/routes.rb
Rails.application.routes.draw do
  resources :recipe_foods
  resources :recipes
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :show, :destroy] 

  resources :foods

  resources :entries do
    collection do
      put :update
    end
  end

  resources :entries do
    resources :entry_foods, only: [:index, :show, :new, :create]
  end

  resources :entry_foods, only: [:edit, :update, :show, :destroy]

  root 'entries#index'

end

app/models/entry_food.rb
class EntryFood < ApplicationRecord
    belongs_to :entry
    belongs_to :food

    validates :entry_id, presence: true
    validates :food_id, presence: true

    def find_food
        Food.find_by(id: self.food_id)
    end

end
  

app/controllers/entry_foods_controller.rb
class EntryFoodsController < ApplicationController

    def show
        @entry_food = EntryFood.find(params[:id])
        @food = @entry_food.food
        @entry = @entry_food.entry
    end
    
    def edit
        @entry_food = EntryFood.find(params[:id])
        @food = @entry_food.food
        @entry = @entry_food.entry
    end

    def update
        @entry_food = EntryFood.find(params[:id])
        @entry_food.update(entry_food_params)
        redirect_to entry_food_path(@entry_food)
    end

    def destroy
        @entry_food = EntryFood.find(params[:id])
        @entry_id = @entry_food.entry_id
        @entry_food.destroy
        @entry = Entry.find(@entry_id)
        redirect_to entry_path(@entry), notice: "The food record has been successfully deleted."
    end

    private

    def entry_food_params
        params.require(:entry_food).permit(:servings, :meal)
    end

end

app/views/entry_foods/edit.html.erb
<h3><strong><%= @food.name %></strong></h3>
<fieldset>
<p><strong>Serving Size: </strong><%= @food.serving_size %> <%= @food.serving_unit %></p>
</fieldset>
<fieldset>
    <%= form_for @entry_food do |f| %>
        <strong><%= f.label :servings, "Number Of Servings:" %></strong>
        <%= f.number_field :servings, placeholder: "n/a", step: :any %><br><br>
        
        <strong><%= f.label :meal, "Meal:" %></strong>
        <%= f.radio_button :meal, "Breakfast" %>
        <%= f.label :meal_breakfast, "Breakfast" %>
        <%= f.radio_button :meal, "Lunch" %>
        <%= f.label :meal_lunch, "Lunch" %>
        <%= f.radio_button :meal, "Dinner" %>
        <%= f.label :meal_dinner, "Dinner" %>
        <%= f.radio_button :meal, "Snack" %>
        <%= f.label :meal_snacks, "Snack" %><br><br>
        
        <%= submit_tag "Submit" %>
    <% end %>
</fieldset>

<% if @entry_food.servings %>
<fieldset>
    <p><strong>Calories: </strong><%= @food.calories * @entry_food.servings %> kcal</p>
    <p><strong>Carbohydrates: </strong><%= @food.carbs * @entry_food.servings %> g</p> 
    <p><strong>Fat: </strong><%= @food.fat * @entry_food.servings %> g</p>
    <p><strong>Protein: </strong><%= @food.protein * @entry_food.servings %> g</p>
    <p><strong>Sodium: </strong><%= @food.sodium * @entry_food.servings %> mg</p>
    <p><strong>Sugars: </strong><%= @food.sugar * @entry_food.servings %> g</p>
</fieldset><br>
<% end %>
<br>
<%= link_to "Back To Entry", entry_path(@entry) %><br>
<%= link_to "Delete Food From Entry", entry_food_path, method: :delete,  data: {confirm: "Are you sure you want to delete this food?"} %>

app/views/entry_foods/show.html.erb
<h3><strong><%= @food.name %></strong></h3>
<fieldset>
<p><strong>Serving Size: </strong><%= @food.serving_size %> <%= @food.serving_unit %></p>
</fieldset>
<fieldset>
    <p>
        <strong>Number Of Servings: </strong>    
        <% if @entry_food.servings %>
            <%= @entry_food.servings %>
        <% else %>
            n/a
        <% end %>
    </p>
    <p><strong>Meal: </strong>
        <% if @entry_food.meal %>
            <%= @entry_food.meal %>
        <% else %>
            Uncategorized
        <% end %>
    </p>

    <%= link_to "Update", edit_entry_food_path(@entry_food) %>
</fieldset>

<% if @entry_food.servings %>
    <fieldset>
        <p><strong>Calories: </strong><%= @food.calories * @entry_food.servings %> kcal</p>
        <p><strong>Carbohydrates: </strong><%= @food.carbs * @entry_food.servings %> g</p> 
        <p><strong>Fat: </strong><%= @food.fat * @entry_food.servings %> g</p>
        <p><strong>Protein: </strong><%= @food.protein * @entry_food.servings %> g</p>
        <p><strong>Sodium: </strong><%= @food.sodium * @entry_food.servings %> mg</p>
        <p><strong>Sugars: </strong><%= @food.sugar * @entry_food.servings %> g</p>
    </fieldset><br>
<% else %>
    <fieldset>
        <p><strong>Calories: </strong><%= @food.calories %> kcal</p>
        <p><strong>Carbohydrates: </strong><%= @food.carbs %> g</p> 
        <p><strong>Fat: </strong><%= @food.fat %> g</p>
        <p><strong>Protein: </strong><%= @food.protein %> g</p>
        <p><strong>Sodium: </strong><%= @food.sodium %> mg</p>
        <p><strong>Sugars: </strong><%= @food.sugar %> g</p>
    </fieldset><br>
<% end %>
<br>
<%= link_to "Delete Food From Entry", entry_food_path, method: :delete,  data: {confirm: "Are you sure you want to delete this food?"} %><br>
<%= link_to "Back To Entry", entry_path(@entry) %>