config/routes.rb
Rails.application.routes.draw do
  resources :recipe_foods
  resources :recipes
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :show, :destroy] 

  resources :foods

  resources :entries do
    collection do
      put :update
    end
  end

  resources :entries do
    resources :entry_foods, only: [:index, :show, :new, :create]
  end

  resources :entry_foods, only: [:edit, :update, :show, :destroy]

  root 'entries#index'

end

app/models/entry.rb
class Entry < ApplicationRecord
    belongs_to :user
    has_many :entry_foods
    has_many :foods, through: :entry_foods

    validates :date, presence: true  
    validates :date, uniqueness: true

    accepts_nested_attributes_for :foods, reject_if: proc { |attributes| attributes['name'].blank? }
    accepts_nested_attributes_for :entry_foods

    def formatted_date
        date = self.date
        date.to_formatted_s(:long)
    end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
    before_action :authentication_required
    
    def index
        @user = @current_user
        @entries = @user.entries.order("date DESC")
    end
    
    def new
        @entry = Entry.new
    end

    def create
        @entry = Entry.new(entry_params)
        if Entry.where(entry_params) != true
            @entry.user = @current_user
            @entry.save
            redirect_to entry_path(@entry)
        else
            flash[:notice] = "An entry already exists for that date."
            render 'new'
        end
    end

    def show
        @entry = Entry.find(params[:id])
        @entry_foods = @entry.entry_foods

        @breakfast_foods = @entry_foods.select{|food| food.meal == "Breakfast"}
        @lunch_foods = @entry_foods.select{|food| food.meal == "Lunch"}
        @dinner_foods = @entry_foods.select{|food| food.meal == "Dinner"}
        @snack_foods = @entry_foods.select{|food| food.meal == "Snack"}
        @uncat_foods = @entry_foods.select{|food| food.meal == nil}
    end

    def edit
        @entry = Entry.find(params[:id])
        @foods = Food.all
        @entry_foods = @entry.entry_foods
    end

    def update
        @entry = Entry.find(params[:id])
        
        if entry_params
            @entry.update(entry_params)

            if food_ids
                food_ids.each do |food_id|
                    entry_food = EntryFood.new
                    entry_food.entry = @entry 
                    entry_food.food_id = food_id
                    entry_food.save
                end
            end
            redirect_to entry_path(@entry), notice: "The entry has been updated."
        else
            flash[:error] = 'Your changes were not saved.'
            render 'edit'
        end
    end

    def destroy
        @entry = Entry.find(params[:id])
        @entry.destroy
        redirect_to root_path, notice: "The entry has been successfully deleted."
    end

    private

    def entry_params
        params.require(:entry).permit(:meal)
    end

    def food_ids
        @food_ids = params[:entry][:food_ids].collect{|id| id.to_i}
    end

end

app/views/entries/edit.html.erb
<%= form_tag entry_path(@entry), method: :put do %>
    <h4>Add Food(s) To Entry</h4>
    <% Food.all.each do |food| %>
        <%= check_box_tag "entry[food_ids][]", food.id %>
        <%= food.name %>
        <br>
    <% end %>
    <br>
    <br>
    <%= submit_tag "Submit" %>
<% end %>


   

app/views/entries/index.html.erb
<h3>Your Entries</h3>
<% if @entries.empty? %>
    <p>You do not have any entries.</p>
<% else %>    
    <ul>
        <% @entries.each do |entry| %>
            <li><%= link_to entry.formatted_date, entry_path(entry) %></li>
        <% end %>
    </ul>
<% end %>
  

app/views/entries/new.html.erb
<section>
    <h1>Create New Entry</h1>
    <%= form_for(@entry) do |f| %>
        <p>
            <%= f.label :date, 'Date:' %>
            <%= f.date_field :date %>
        </p>
        <br>
        
        

        <%= f.submit %>
    <% end %>
</section>
        
   

app/views/entries/show.html.erb
<h1> <%= @entry.formatted_date %></h1>

<% if @entry_foods.empty? %>
    You have not logged any foods for this entry.
<% end %>

<div class="breakfast">
    <h2>Breakfast</h2>
    <fieldset>
    <ul>
    <% @breakfast_foods.each do |entry_food| %>
        <li>
            <%= link_to entry_food.food.name, entry_food_path(entry_food) %>
        </li>
        <% end %>
    </ul>
    </fieldset>
</div>

<div class="lunch">
    <h2>Lunch</h2>
    <fieldset>
    <ul>
        <% @lunch_foods.each do |entry_food| %>
            <li>
                <%= link_to entry_food.food.name, entry_food_path(entry_food) %>
            </li>
        <% end %>
    </ul>
    </fieldset>
</div>

<div class="dinner">
    <h2>Dinner</h2>
    <fieldset>
    <ul>
    <% @dinner_foods.each do |entry_food| %>
        <li>
            <%= link_to entry_food.food.name, entry_food_path(entry_food) %>
        </li>
    <% end %>
</ul>
</fieldset>
</div>

<div class="snacks">
    <h2>Snacks</h2>
    <fieldset>
    <ul>
    <% @snack_foods.each do |entry_food| %>
        <li>
            <%= link_to entry_food.food.name, entry_food_path(entry_food) %>
        </li>
    <% end %>
</ul>
</fieldset>
</div>

<div class="uncategorized">
    <h2>Uncategorized</h2>
    <fieldset>
    <ul>
    <% @uncat_foods.each do |entry_food| %>
        <li>
            <%= link_to entry_food.food.name, entry_food_path(entry_food) %>
        </li>
    <% end %>
</ul>
</fieldset>
</div>

<br>
<br>
<%= link_to "Update Entry", edit_entry_path %><br>
<%= link_to "Delete Entry", entry_path, method: :delete, data: {confirm: "Are you sure you want to delete this entry?"} %>