config/routes.rb
Rails.application.routes.draw do
  resources :recipe_foods
  resources :recipes
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :show, :destroy] 

  resources :foods

  resources :entries do
    collection do
      put :update
    end
  end

  resources :entries do
    resources :entry_foods, only: [:index, :show, :new, :create]
  end

  resources :entry_foods, only: [:edit, :update, :show, :destroy]

  root 'entries#index'

end

app/models/food.rb
class Food < ApplicationRecord
    has_many :entry_foods
    has_many :recipe_foods

    validates :name, presence: true
    validates :serving_unit, presence: true
    validates :serving_size, presence: true
    validates :calories, presence: true
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
    def index
        if params[:entry_id]
            @entry = Entry.find(params[:entry_id])
            @foods = @entry.foods
        elsif params[:recipe_id]
            @recipe = Recipe.find(params[:recipe_id])
            @foods = @recipe.foods
        else
            @foods = Food.all
        end
    end
    
    def new
        @food = Food.new
    end

    def create
        @food = Food.new(food_params)
        
        if @food.valid?
            @food.save
            redirect_to food_path(@food)
        else
            render :new
        end
    end

    def show
        @food = Food.find(params[:id])
    end
    
    def edit
        @food = Food.find(params[:id])
    end

    def update
        @food = Food.find(params[:id])
        @food.update(food_params)
        redirect_to food_path(@food)
    end

    def destroy
        @food = Food.find(params[:id])
        @food.destroy
        redirect_to foods_path, notice: "The food record has been successfully deleted."
    end

    private

    def food_params
        params.require(:food).permit(:name, :serving_unit, :serving_size, :calories, :carbs, :fat, :protein, :sodium, :sugar)
    end

end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= link_to "Home", root_path %><br>

<%= form_for @food do |f| %>
    <%= f.label :name, "Name:" %>
    <%= f.text_field :name, placeholder: "n/a" %><br>

    <% if params[:entry_id] %>    
        <%= f.hidden_field :entry_id %>
    <% elsif params[:recipe_id] %>
        <%= f.hidden_field :recipe_id %>
    <% end %>

    <%= f.label :serving_size, "Serving Size:" %>
    <%= f.number_field :serving_size, placeholder: "n/a", step: :any %>

    <%= f.label :serving_unit_grams, "g" %>
    <%= f.radio_button :serving_unit, "g" %>
    <%= f.label :serving_unit_tbsp, "tbsp(s)" %>
    <%= f.radio_button :serving_unit, "tbsp(s)" %>
    <%= f.label :serving_unit_tsp, "tsp(s)" %>
    <%= f.radio_button :serving_unit, "tsp(s)" %>
    <%= f.label :serving_unit_cups, "cup(s)" %>
    <%= f.radio_button :serving_unit, "cup(s)" %><br>
    
    <%= f.label :calories, "Calories (kcal):" %>
    <%= f.number_field :calories, placeholder: "n/a", step: :any %><br>

    <%= f.label :carbs, "Carbohydrates (g):" %>
    <%= f.number_field :carbs, placeholder: "n/a", step: :any %><br>

    <%= f.label :fat, "Fat (g):" %>
    <%= f.number_field :fat, placeholder: "n/a", step: :any %><br>

    <%= f.label :protein, "Protein (g):" %>
    <%= f.number_field :protein, placeholder: "n/a", step: :any %><br>

    <%= f.label :sodium, "Sodium (mg):" %>
    <%= f.number_field :sodium, placeholder: "n/a", step: :any %><br>

    <%= f.label :sugar, "Sugars (g):" %>
    <%= f.number_field :sugar, placeholder: "n/a", step: :any %><br><br>
    
    <%= f.submit %>
<% end %>

app/views/foods/edit.html.erb
<%= link_to "Home", root_path %><br>

<h1>Update Food Record</h1>

<%= form_for @food do |f| %>
    <%= f.label :name, "Name:" %>
    <%= f.text_field :name, placeholder: "n/a" %><br>

    <%= f.label :serving_size, "Serving Size:" %>
    <%= f.number_field :serving_size, placeholder: "n/a", step: :any %>

    <%= f.label :serving_unit_grams, "g" %>
    <%= f.radio_button :serving_unit, "g" %>
    <%= f.label :serving_unit_tbsp, "tbsp(s)" %>
    <%= f.radio_button :serving_unit, "tbsp(s)" %>
    <%= f.label :serving_unit_tsp, "tsp(s)" %>
    <%= f.radio_button :serving_unit, "tsp(s)" %>
    <%= f.label :serving_unit_cups, "cup(s)" %>
    <%= f.radio_button :serving_unit, "cup(s)" %><br>
    
    <%= f.label :calories, "Calories (kcal):" %>
    <%= f.number_field :calories, placeholder: "n/a", step: :any %><br>

    <%= f.label :carbs, "Carbohydrates (g):" %>
    <%= f.number_field :carbs, placeholder: "n/a", step: :any %><br>

    <%= f.label :fat, "Fat (g):" %>
    <%= f.number_field :fat, placeholder: "n/a", step: :any %><br>

    <%= f.label :protein, "Protein (g):" %>
    <%= f.number_field :protein, placeholder: "n/a", step: :any %><br>

    <%= f.label :sodium, "Sodium (mg):" %>
    <%= f.number_field :sodium, placeholder: "n/a", step: :any %><br>

    <%= f.label :sugar, "Sugars (g):" %>
    <%= f.number_field :sugar, placeholder: "n/a", step: :any %><br><br>
    
    <%= f.submit "Update" %>
<% end %>


<%= link_to "Delete Record", food_path, method: :delete, data: {confirm: "Are you sure you want to delete this food record?"} %>

app/views/foods/index.html.erb
<h1>Food Database</h1>

<div>
    <ul>
        <% @foods.each do |food| %>
            <% if food.name != nil %>
                <li><%= link_to food.name, food_path(food) %></li>
            <% end %>
        <% end %>
    </ul>
</div>

<div>
    <%= link_to "Create New Food Record", new_food_path %><br>
    <%= link_to "Back", root_path %><br>
</div>

app/views/foods/new.html.erb
<h1>New Food Record</h1>

<%= form_with model: [@food], local: true do |f| %>
    <strong><%= f.label :name, "Name:" %></strong>
    <%= f.text_field :name, placeholder: "n/a" %><br>

    <strong><%= f.label :serving_size, "Serving Size:" %></strong>
    <%= f.number_field :serving_size, placeholder: "n/a", step: :any %>

    <%= f.radio_button :serving_unit, "g" %>
    <%= f.label :serving_unit_grams, "g" %>
    <%= f.radio_button :serving_unit, "tbsp(s)" %>
    <%= f.label :serving_unit_tbsp, "tbsp(s)" %>
    <%= f.radio_button :serving_unit, "tsp(s)" %>
    <%= f.label :serving_unit_tsp, "tsp(s)" %>
    <%= f.radio_button :serving_unit, "cup(s)" %>
    <%= f.label :serving_unit_cups, "cup(s)" %><br>
    
    <strong><%= f.label :calories, "Calories (kcal):" %></strong>
    <%= f.number_field :calories, placeholder: "n/a", step: :any %><br>

    <strong><%= f.label :carbs, "Carbohydrates (g):" %></strong>
    <%= f.number_field :carbs, placeholder: "n/a", step: :any %><br>

    <strong><%= f.label :fat, "Fat (g):" %></strong>
    <%= f.number_field :fat, placeholder: "n/a", step: '0.01' %><br>

    <strong><%= f.label :protein, "Protein (g):" %></strong>
    <%= f.number_field :protein, placeholder: "n/a", step: :any %><br>

    <strong><%= f.label :sodium, "Sodium (mg):" %></strong>
    <%= f.number_field :sodium, placeholder: "n/a", step: :any %><br>

    <strong><%= f.label :sugar, "Sugars (g):" %></strong>
    <%= f.number_field :sugar, placeholder: "n/a", step: :any %><br><br>
    
    <%= f.submit "Create" %>
<% end %>

app/views/foods/show.html.erb
<h3><strong><%= @food.name %></strong></h3>

<p><strong>Calories: </strong><%= @food.calories %> kcal</p>
<p><strong>Carbohydrates: </strong><%= @food.carbs %> g</p> 
<p><strong>Fat: </strong><%= @food.fat %> g</p>
<p><strong>Protein: </strong><%= @food.protein %> g</p>
<p><strong>Sodium: </strong><%= @food.sodium %> mg</p>
<p><strong>Sugars: </strong><%= @food.sugar %> g</p>

<%= link_to "Edit Record", edit_food_path %><br>
<%= link_to "Delete Record", food_path, method: :delete, data: {confirm: "Are you sure you want to delete this food record?"} %><br>